"""add llm_call ledger table

Revision ID: 517bbce24fb9
Revises: 99d97ee622d2
Create Date: 2026-08-21 22:19:17.821574

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '517bbce24fb9'
down_revision: str | None = '99d97ee622d2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_call',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('agent_role', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('prompt_hash', sa.String(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OK', 'VALIDATION_FAILED', 'ERROR', name='llm_call_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt >= 1', name=op.f('ck_llm_call_attempt_at_least_one')),
    sa.CheckConstraint('cost_usd IS NULL OR cost_usd >= 0', name=op.f('ck_llm_call_cost_usd_non_negative')),
    sa.CheckConstraint('input_tokens IS NULL OR input_tokens >= 0', name=op.f('ck_llm_call_input_tokens_non_negative')),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name=op.f('ck_llm_call_llm_call_latency_ms_non_negative')),
    sa.CheckConstraint('output_tokens IS NULL OR output_tokens >= 0', name=op.f('ck_llm_call_output_tokens_non_negative')),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], name=op.f('fk_llm_call_incident_id_incident')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_call'))
    )
    op.create_index(op.f('ix_llm_call_incident_id'), 'llm_call', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_call_incident_id'), table_name='llm_call')
    op.drop_table('llm_call')
    # ### end Alembic commands ###

    # op.drop_table() does not cascade-drop the Postgres ENUM type it used —
    # see 99d97ee622d2's downgrade() for the same fix applied to T1's tables.
    sa.Enum(name='llm_call_status').drop(op.get_bind(), checkfirst=True)
