"""add unique constraint on verification_record.execution_id

Revision ID: 596606b61f0e
Revises: 95147f49216f
Create Date: 2026-08-31 16:39:38.614913

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '596606b61f0e'
down_revision: str | None = '95147f49216f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_record_execution_id'), table_name='verification_record')
    op.create_unique_constraint(op.f('uq_verification_record_execution_id'), 'verification_record', ['execution_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_verification_record_execution_id'), 'verification_record', type_='unique')
    op.create_index(op.f('ix_verification_record_execution_id'), 'verification_record', ['execution_id'], unique=False)
    # ### end Alembic commands ###
