"""initial schema

Revision ID: 99d97ee622d2
Revises: 
Create Date: 2026-08-11 21:55:30.909002

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99d97ee622d2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('image_tag', sa.String(), nullable=False),
    sa.Column('config_diff', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deployed_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployment'))
    )
    op.create_index(op.f('ix_deployment_deployed_at'), 'deployment', ['deployed_at'], unique=False)
    op.create_index(op.f('ix_deployment_service'), 'deployment', ['service'], unique=False)
    op.create_table('incident',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('SEV1', 'SEV2', 'SEV3', 'SEV4', name='severity'), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'TRIAGING', 'INVESTIGATING', 'AWAITING_APPROVAL', 'REMEDIATING', 'VERIFYING', 'RESOLVED', 'CLOSED', 'ESCALATED', 'FAILED', name='incident_status'), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('environment', sa.Enum('LOCAL', 'STAGING', 'PROD', name='environment'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident'))
    )
    op.create_index(op.f('ix_incident_fingerprint'), 'incident', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_incident_service'), 'incident', ['service'], unique=False)
    op.create_index(op.f('ix_incident_status'), 'incident', ['status'], unique=False)
    op.create_table('service_dependency',
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('depends_on', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('service', 'depends_on', name=op.f('pk_service_dependency'))
    )
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('tool', sa.String(), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('result_digest', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('OK', 'ERROR', name='evidence_status'), nullable=False),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name=op.f('ck_evidence_latency_ms_non_negative')),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], name=op.f('fk_evidence_incident_id_incident')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    op.create_index(op.f('ix_evidence_incident_id'), 'evidence', ['incident_id'], unique=False)
    op.create_table('incident_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor_type', sa.Enum('SYSTEM', 'LLM', 'HUMAN', name='actor_type'), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], name=op.f('fk_incident_event_incident_id_incident')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_event')),
    sa.UniqueConstraint('incident_id', 'seq', name=op.f('uq_incident_event_incident_id'))
    )
    op.create_index(op.f('ix_incident_event_incident_id'), 'incident_event', ['incident_id'], unique=False)
    op.create_table('incident_signal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('alert_fingerprint', sa.String(), nullable=False),
    sa.Column('alertname', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], name=op.f('fk_incident_signal_incident_id_incident')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_signal')),
    sa.UniqueConstraint('incident_id', 'alert_fingerprint', name=op.f('uq_incident_signal_incident_id'))
    )
    op.create_index(op.f('ix_incident_signal_incident_id'), 'incident_signal', ['incident_id'], unique=False)
    op.create_table('postmortem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], name=op.f('fk_postmortem_incident_id_incident')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_postmortem'))
    )
    op.create_index(op.f('ix_postmortem_incident_id'), 'postmortem', ['incident_id'], unique=False)
    op.create_table('rca',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('agent_version', sa.String(), nullable=False),
    sa.Column('prompt_hash', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], name=op.f('fk_rca_incident_id_incident')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rca'))
    )
    op.create_index(op.f('ix_rca_incident_id'), 'rca', ['incident_id'], unique=False)
    op.create_table('hypothesis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rca_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('counter_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('demoted_reason', sa.Text(), nullable=True),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name=op.f('ck_hypothesis_confidence_in_unit_interval')),
    sa.ForeignKeyConstraint(['rca_id'], ['rca.id'], name=op.f('fk_hypothesis_rca_id_rca')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hypothesis'))
    )
    op.create_index(op.f('ix_hypothesis_rca_id'), 'hypothesis', ['rca_id'], unique=False)
    op.create_table('remediation_proposal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('rca_id', sa.Uuid(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], name=op.f('fk_remediation_proposal_incident_id_incident')),
    sa.ForeignKeyConstraint(['rca_id'], ['rca.id'], name=op.f('fk_remediation_proposal_rca_id_rca')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remediation_proposal'))
    )
    op.create_index(op.f('ix_remediation_proposal_incident_id'), 'remediation_proposal', ['incident_id'], unique=False)
    op.create_index(op.f('ix_remediation_proposal_rca_id'), 'remediation_proposal', ['rca_id'], unique=False)
    op.create_table('action',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_resource', sa.String(), nullable=False),
    sa.Column('policy_decision', sa.Enum('AUTO_APPROVE', 'REQUIRE_APPROVAL', 'FORBID', name='policy_effect'), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['remediation_proposal.id'], name=op.f('fk_action_proposal_id_remediation_proposal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_action_idempotency_key'))
    )
    op.create_index(op.f('ix_action_proposal_id'), 'action', ['proposal_id'], unique=False)
    op.create_table('approval_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action_id', sa.Uuid(), nullable=False),
    sa.Column('quorum', sa.Integer(), nullable=False),
    sa.Column('required_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], name=op.f('fk_approval_request_action_id_action')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_request'))
    )
    op.create_index(op.f('ix_approval_request_action_id'), 'approval_request', ['action_id'], unique=False)
    op.create_table('execution_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], name=op.f('fk_execution_record_action_id_action')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_record'))
    )
    op.create_index(op.f('ix_execution_record_action_id'), 'execution_record', ['action_id'], unique=False)
    op.create_table('policy_decision',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('effect', sa.Enum('AUTO_APPROVE', 'REQUIRE_APPROVAL', 'FORBID', name='policy_effect'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], name=op.f('fk_policy_decision_action_id_action')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_decision'))
    )
    op.create_index(op.f('ix_policy_decision_action_id'), 'policy_decision', ['action_id'], unique=False)
    op.create_table('approval_decision',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('approval_request_id', sa.Uuid(), nullable=False),
    sa.Column('decider_id', sa.String(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVE', 'REJECT', name='approval_decision_type'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_request.id'], name=op.f('fk_approval_decision_approval_request_id_approval_request')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_decision'))
    )
    op.create_index(op.f('ix_approval_decision_approval_request_id'), 'approval_decision', ['approval_request_id'], unique=False)
    op.create_table('verification_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('metric_snapshots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['execution_record.id'], name=op.f('fk_verification_record_execution_id_execution_record')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_record'))
    )
    op.create_index(op.f('ix_verification_record_execution_id'), 'verification_record', ['execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_record_execution_id'), table_name='verification_record')
    op.drop_table('verification_record')
    op.drop_index(op.f('ix_approval_decision_approval_request_id'), table_name='approval_decision')
    op.drop_table('approval_decision')
    op.drop_index(op.f('ix_policy_decision_action_id'), table_name='policy_decision')
    op.drop_table('policy_decision')
    op.drop_index(op.f('ix_execution_record_action_id'), table_name='execution_record')
    op.drop_table('execution_record')
    op.drop_index(op.f('ix_approval_request_action_id'), table_name='approval_request')
    op.drop_table('approval_request')
    op.drop_index(op.f('ix_action_proposal_id'), table_name='action')
    op.drop_table('action')
    op.drop_index(op.f('ix_remediation_proposal_rca_id'), table_name='remediation_proposal')
    op.drop_index(op.f('ix_remediation_proposal_incident_id'), table_name='remediation_proposal')
    op.drop_table('remediation_proposal')
    op.drop_index(op.f('ix_hypothesis_rca_id'), table_name='hypothesis')
    op.drop_table('hypothesis')
    op.drop_index(op.f('ix_rca_incident_id'), table_name='rca')
    op.drop_table('rca')
    op.drop_index(op.f('ix_postmortem_incident_id'), table_name='postmortem')
    op.drop_table('postmortem')
    op.drop_index(op.f('ix_incident_signal_incident_id'), table_name='incident_signal')
    op.drop_table('incident_signal')
    op.drop_index(op.f('ix_incident_event_incident_id'), table_name='incident_event')
    op.drop_table('incident_event')
    op.drop_index(op.f('ix_evidence_incident_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_table('service_dependency')
    op.drop_index(op.f('ix_incident_status'), table_name='incident')
    op.drop_index(op.f('ix_incident_service'), table_name='incident')
    op.drop_index(op.f('ix_incident_fingerprint'), table_name='incident')
    op.drop_table('incident')
    op.drop_index(op.f('ix_deployment_service'), table_name='deployment')
    op.drop_index(op.f('ix_deployment_deployed_at'), table_name='deployment')
    op.drop_table('deployment')
    # ### end Alembic commands ###
    # Postgres ENUM types are independent objects that op.drop_table() does not
    # cascade-drop, so a downgrade that stopped above would leave them behind
    # and a re-upgrade would then fail with "type already exists".
    sa.Enum(name='approval_decision_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='policy_effect').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='actor_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='evidence_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='environment').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='incident_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='severity').drop(op.get_bind(), checkfirst=True)
