"""add approval_decision immutability and quorum constraint

Revision ID: b157c1d01b3b
Revises: 517bbce24fb9
Create Date: 2026-08-26 22:08:40.889702

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b157c1d01b3b'
down_revision: str | None = '517bbce24fb9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_approval_decision_approval_request_id'), 'approval_decision', ['approval_request_id', 'decider_id'])
    # ### end Alembic commands ###

    # T9 (design doc §1.10): "Decision rows are immutable" is enforced here,
    # not just by application code never issuing an UPDATE/DELETE — a
    # trigger is the only way to make that a real guarantee rather than a
    # convention every future caller has to remember.
    op.execute(
        """
        CREATE FUNCTION approval_decision_immutable() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'approval_decision rows are immutable (id=%)', OLD.id;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER approval_decision_no_update
        BEFORE UPDATE ON approval_decision
        FOR EACH ROW EXECUTE FUNCTION approval_decision_immutable()
        """
    )
    op.execute(
        """
        CREATE TRIGGER approval_decision_no_delete
        BEFORE DELETE ON approval_decision
        FOR EACH ROW EXECUTE FUNCTION approval_decision_immutable()
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS approval_decision_no_delete ON approval_decision")
    op.execute("DROP TRIGGER IF EXISTS approval_decision_no_update ON approval_decision")
    op.execute("DROP FUNCTION IF EXISTS approval_decision_immutable()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_approval_decision_approval_request_id'), 'approval_decision', type_='unique')
    # ### end Alembic commands ###
