"""T1 done-criterion: the Alembic migration applies cleanly to a fresh local
Postgres. This runs it against a real, ephemeral Postgres container rather
than asserting anything about the migration file's contents — a migration
that looks right and a migration that actually applies are different
claims, and this test only trusts the second one."""

from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import create_engine, inspect

DATABASE_DIR = Path(__file__).resolve().parent.parent

EXPECTED_TABLES = {
    "incident",
    "incident_event",
    "incident_signal",
    "evidence",
    "hypothesis",
    "rca",
    "remediation_proposal",
    "action",
    "policy_decision",
    "approval_request",
    "approval_decision",
    "execution_record",
    "verification_record",
    "postmortem",
    "service_dependency",
    "deployment",
}


def _alembic_config() -> Config:
    config = Config(str(DATABASE_DIR / "alembic.ini"))
    config.set_main_option("script_location", str(DATABASE_DIR / "alembic"))
    return config


def test_migration_upgrades_a_fresh_database_to_the_full_schema(
    postgres_url: str, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("AIC_DATABASE_URL", postgres_url)
    command.upgrade(_alembic_config(), "head")

    engine = create_engine(postgres_url)
    try:
        table_names = set(inspect(engine).get_table_names())
    finally:
        engine.dispose()

    assert table_names >= EXPECTED_TABLES


def test_migration_matches_the_orm_models_exactly(
    postgres_url: str, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Guards against models.py and the committed migration drifting apart —
    fails if autogenerate would detect any further changes at head."""
    monkeypatch.setenv("AIC_DATABASE_URL", postgres_url)
    config = _alembic_config()
    command.upgrade(config, "head")

    command.check(config)  # raises AutogenerateDiffsDetected on any drift


def test_migration_downgrade_is_clean_and_head_is_reapplicable(
    postgres_url: str, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A downgrade that leaves orphaned objects behind (e.g. Postgres ENUM
    types, which op.drop_table does not cascade-drop) would make the next
    upgrade fail with 'type already exists' — this catches that class of bug."""
    monkeypatch.setenv("AIC_DATABASE_URL", postgres_url)
    config = _alembic_config()

    command.upgrade(config, "head")
    command.downgrade(config, "base")

    engine = create_engine(postgres_url)
    try:
        remaining = set(inspect(engine).get_table_names()) - {"alembic_version"}
    finally:
        engine.dispose()
    assert remaining == set()

    command.upgrade(config, "head")
